import type { Metadata } from 'next';
import './globals.css';
import { Quantico, Inter } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const quantico = Quantico({
  variable: '--font-quantico',
  subsets: ['latin'],
  style: ['normal'],
  weight: '700',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`h-full ${quantico.variable} ${inter.variable} antialiased`}
    >
      <body className='min-h-full flex flex-col'>
        {/* <Navbar /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
